//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardSales.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Access_token {
            get {
                return ((string)(this["Access_token"]));
            }
            set {
                this["Access_token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsIbHR7Eu6nQEW7GzVj7al6FmZ8IW1U4bcG0IOehu7W8TE14GKEPotzZpBkMyHI7gotWpNlCJjw4fisDLnM5RsDdbKJEFMVfwjFdPXnywrJ15421D4+Ve/UXtcqM8ocriPlPciRlAb/YF9Yk1QHht+k0FjREivX8vV1KSlE2t36B/DUvfwVF3w+Z28Kf8MCau4QLI7nIVSuRL3IxJSXAA6g6ZZl+9YKnS3Z+f93D5TX7BpaxuE9unh22nAA7vktYjCxDa8Ujy/D8wQIBecSWMVwTpz7vzRgBdL2JoIY5jz/R4GsdmqAy80Wp4OPl7gK61CJan4J12KDWVqBMOAcdzCwIDAQAB")]
        public string Pub_key {
            get {
                return ((string)(this["Pub_key"]));
            }
            set {
                this["Pub_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aa62007")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"F7d1a3vLwL4c/SaXO5b5ADqslyMm+l5U1wFaXpK84Jg1KYnZGHKIPTlYfJFifTuG4GCaT/cbk6/KBw3Ac0Qmumsmp+xnOFA50Be2lL8ejtmt5MxrNbcVbitMzxSmetVBOZs3rn2JTWm/SX8qz8JuxVULygM3rx6eRQ3cdE9mkq+5sOoAN9VhIn+14oAbe8RtjOZ2lbT7y7cXmkel0n2y38eBBi6pUkvI4JqM48F15j7NlGSdpNnfcxvLd1D3u2mFl+hso7KQnhecA47Cgiur35xSwOWJxO7rHIDyMi2QImS1JdOvacPzgIy28PA/MvbLRrJlsAwP0baDGHID1jcYCQ==")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
    }
}
